job:
  before_script:
    - git clean -fd

before_script:
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apk update -y && apk add openssh-client git -y )'
    # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  - rm -rf ~/.ssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'deploy.blueclerk.com' >> ~/.ssh/known_hosts

stages:
  - dev

deploy_to_dokku_dev:
  stage: dev
  script:
    - git push -f dokku@deploy.blueclerk.com:blueclerk-node-api-dev HEAD:refs/for/dev
