# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2
definitions:
  services:
    docker:
      memory: 2048

pipelines:
  branches:
    staging:
      - step:
          #python image with aws-cli installed
          image: atlassian/pipelines-awscli
          services:
            - docker
          script:
            - export REPOSITORY_URL=744236993133.dkr.ecr.us-east-1.amazonaws.com/blueclerk-staging
            - export REGION=us-east-1
            - export TASK_DEFINITION_NAME=blueclerk-staging
            - export CLUSTER_NAME=blueclerk-new-tst-stg
            - export SERVICE_NAME=blueclerk-new-staging
            - export SECRET_ID=blueclerk-staging
            # aws login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            # docker
            - export IMAGE_TAG="${BITBUCKET_COMMIT::7}"
            - DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --region ${AWS_DEFAULT_REGION} --output text --query SecretString | jq ".DATABASE_URL" | tr -d '"')
            - docker build -t ${REPOSITORY_URL}:$IMAGE_TAG --build-arg node_environment=staging --build-arg database_url=$DATABASE_URL .
            - docker push ${REPOSITORY_URL}:$IMAGE_TAG
            - docker tag ${REPOSITORY_URL}:$IMAGE_TAG ${REPOSITORY_URL}:latest
            - docker push ${REPOSITORY_URL}:latest
            - echo $REPOSITORY_URL:$IMAGE_TAG
            - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${REGION}")
            - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URL:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
            - echo "${NEW_CONTAINER_DEFINITION}"
            - echo "Registering new container definition..."
            - aws ecs register-task-definition --region "${REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --memory 2048  --execution-role-arn "arn:aws:iam::744236993133:role/ecs-task-secret-manager"
            - echo "Updating the service..."
            - aws ecs update-service --region "${REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"
    test:
      - step:
          #python image with aws-cli installed
          image: atlassian/pipelines-awscli
          services:
            - docker
          script:
            - export REPOSITORY_URL=744236993133.dkr.ecr.us-east-1.amazonaws.com/blueclerk-test
            - export REGION=us-east-1
            - export TASK_DEFINITION_NAME=blueclerk-test
            - export CLUSTER_NAME=blueclerk-new-tst-stg
            - export SERVICE_NAME=blueclerk-new-test
            - export SECRET_ID=blueclerk-test
            # aws login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            # docker
            - export IMAGE_TAG="${BITBUCKET_COMMIT::7}"
            - DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --region ${AWS_DEFAULT_REGION} --output text --query SecretString | jq ".DATABASE_URL" | tr -d '"')
            - docker build -t ${REPOSITORY_URL}:$IMAGE_TAG --build-arg node_environment=test --build-arg database_url=$DATABASE_URL .
            - docker push ${REPOSITORY_URL}:$IMAGE_TAG
            - docker tag ${REPOSITORY_URL}:$IMAGE_TAG ${REPOSITORY_URL}:latest
            - docker push ${REPOSITORY_URL}:latest
            - echo $REPOSITORY_URL:$IMAGE_TAG
            - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${REGION}")
            - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URL:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
            - echo "${NEW_CONTAINER_DEFINITION}"
            - echo "Registering new container definition..."
            - aws ecs register-task-definition --region "${REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --memory 2048 --execution-role-arn "arn:aws:iam::744236993133:role/ecs-task-secret-manager"
            - echo "Updating the service..."
            - aws ecs update-service --region "${REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"
    master:
      - step:
          #python image with aws-cli installed
          image: atlassian/pipelines-awscli
          services:
            - docker
          script:
            - export REPOSITORY_URL=744236993133.dkr.ecr.us-east-1.amazonaws.com/blueclerk-backend
            - export REGION=us-east-1
            - export TASK_DEFINITION_NAME=blueclerk-backend
            - export CLUSTER_NAME=blueclerk
            - export SERVICE_NAME=blueclerk-api
            # aws login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            # docker
            - export IMAGE_TAG="${BITBUCKET_COMMIT::7}"
            - DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $SERVICE_NAME --region ${AWS_DEFAULT_REGION} --output text --query SecretString | jq ".DATABASE_URL" | tr -d '"')
            - docker build -t ${REPOSITORY_URL}:$IMAGE_TAG --build-arg node_environment=production --build-arg database_url=$DATABASE_URL .
            - docker push ${REPOSITORY_URL}:$IMAGE_TAG
            - docker tag ${REPOSITORY_URL}:$IMAGE_TAG ${REPOSITORY_URL}:latest
            - docker push ${REPOSITORY_URL}:latest
            - echo $REPOSITORY_URL:$IMAGE_TAG
            - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${REGION}")
            - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URL:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
            - echo "${NEW_CONTAINER_DEFINITION}"
            - echo "Registering new container definition..."
            - aws ecs register-task-definition --region "${REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}" --memory 2048 --execution-role-arn "arn:aws:iam::744236993133:role/ecs-task-secret-manager"
            - echo "Updating the service..."
            - aws ecs update-service --region "${REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"

