version: '2.1'

services:
  blueclerk-node-api:
    image: blueclerk-node-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3006:3006
      # - 3006:80
      # - 3006:443