export const Status = {
    OK: 200,
    Created: 201,
    MissingParameters: 400,
    Unauthenticated: 401,
    Forbidden: 403,
    NotFound: 404,
    InternalError: 500,
    Error: 0,
    Success: 1,
    TagAssociated: 2,
    TagNotAssociated: 3,
    QBUnauthorized: 4,
    InvalidEquipment: 5,
    TimeOut: 503
}

export const enum TagType {
    CustomerEquipmentTag,
    LocationTag
}

export const Messages = {
    MissingParams: 'Parameters are missing',
    InvalidEmailPassword: 'Invalid email/password.',
    InvalidEmail: 'invalid format (not email format)',
    GenericError: 'Can\'t process now. Please try again later.',
    DuplicateEmail: 'Email address already registered. Please try with some other email address',
    CompanyDuplicateEmail: 'Company Email address already registered. Please try with some other email address',
    UnAuthorized: 'You are not authorized for this action. Please contact admin for more details.',
    AccountDeleted: 'You account has been deleted. Please contact admin for more details.',
    AgreeToTermAndConditions: 'You must agree to terms and conditions of blueclerk.',
    UserExists: 'User already exists.',
    TagAssociated: 'Tag is associated with customer',
    TagNotAssociated: 'Tag is not associated with customer',
    QBUnAuthorized: 'Quickbooks authorization failed',
    InternalServerError: 'There was an internal server error. Please try again later.',
    Required: 'is required',
    WrongId: 'Id passed must be a single String of 12 bytes or a string of 24 hex characters',
    NotificationNotFound: "Notification not found",
    JobCannotBeStarted: `You can't start this job, it is already`,
    TaskCannotBeStarted: `You can't start this task/job type, it is already`,
    TaskCannotBeUpdated: `You can't update this task/job type, it is already`,
    TaskNotFound: 'Task/job type not found in this Job.'
}

export const enum Role {
    OFFICE_ADMIN,
    TECHNICIAN,
    MANAGER,
    COMPANY_ADMIN,
    ADMIN_EMPLOYEE,
    GLOBAL_ADMIN,
    CUSTOMER,
    CUSTOMER_CONTACT
}

export const enum OrderStatus {
    PLACED,
    PAID,
    CONFIRMED,
    DISPATCHED,
    DELIVERED
}

export const enum EquipmentStatus {
    CHECKIN,
    CHECKOUT
}

export const enum JobStatus {
    PENDING,
    STARTED,
    FINISHED,
    CANCELED,
    RESCHEDULED,
    PAUSED,
    INCOMPLETE
}

export const enum ServiceTicketStatus {
    ACTIVE,
    ARCHIVED,
    REACTIVE
}

export const enum ServiceTicketSource {
    WEB = 'web',
    BLUECLERK = 'blueclerk'
}

export const enum SocketEvents {
    NOTIFICATION_CENTER = 'notification_center',
    CREATESERVICETICKET = 'createServiceTicketMsg',
    ALL_OPEN_SERVICE_TICKETS = 'all_open_service_tickets',
    ALL_SCHEDULED_JOBS = 'all_scheduled_jobs',
    ALL_JOBS = 'all_jobs'
}

export const enum ContractStatus {
    PENDING,
    ACCEPTED,
    CANCELED,
    REJECTED,
    FINISHED,
    ACCOUNT_NOT_CREATED
}

export const enum PurchaseOrderStatus {
    PENDING,
    APPROVED,
    CANCELED
}

export const enum EstimateStatus {
    PENDING,
    APPROVED,
    CANCELED
}


export const enum EmployeeStatus {
    INACTIVE,
    ACTIVE
}

export const enum CompanyType {
    SUBSCRIBED,
    FREE,
}

export enum NotificationTypes {
    SERVICE_TICKET_CREATED = 'ServiceTicketCreated',
    CONTRACT_INVITATION = 'ContractInvitation',
    CONTRACT_ACCEPTED = 'ContractAccepted',
    CONTRACT_CANCELED = 'ContractCanceled',
    CONTRACT_REJECTED = 'ContractRejected',
    CONTRACT_FINISHED = 'ContractFinished',
    JOB_RESCHEDULED = 'JobRescheduled',
    COMPANY_INVOICE_FAILED = 'CompanyInvoiceFailed'
}

export enum PaymentTermNames {
    DUE_ON_RECEIPT = 'Due on Receipt',
    NET_15 = 'Net 15',
    NET_30 = 'Net 30'
}

export enum InvoiceStatus {
    UNPAID = 'UNPAID',
    PARTIALLY_PAID = 'PARTIALLY_PAID',
    PAID = 'PAID'
}

export enum PaymentTypes {
    ACH = 'ACH',
    BANK_WIRE = 'Bank Wire',
    CREDIT_DEBIT_CARD = 'Credit Card/Debit Card',
    CHECK = 'Check',
    CASH = 'Cash',
}

export enum QBEntityNames {
    CUSTOMER = 'Customer',
    ITEM = 'Item',
    PAYMENT = 'Payment',
    TERM = 'Term'
}

export enum QBEntityOperations {
    CREATE = 'Create',
    UPDATE = 'Update',
    DELETE = 'Delete',
    VOID = 'Void'
}

export enum DefaultCommission {
    VENDOR_COMMISSION = 0,
    EMPLOYEE_COMMISSION = 0,
}

export const DefaultPageSize = 30;

export const enum Permissions {
    None,
    Permission_Get_All,
    Permission_Get_Office_Admin,
    Permission_Get_Tech,
    Permission_Get_Manager,
    Permission_Get_Employee,
    Permission_Update_Default,
    Permission_Update_Employee,
    User_Create_Manager,
    User_Get_Manager,
    User_Create_Technician,
    User_Get_Technician,
    User_Create_Office_Admin,
    User_Get_Office_Admin,
    User_Update_Profile,
    User_Change_Password,
    User_Delete_Employee,
    User_Activate_Employee,
    User_Get_All_Employees,
    Update_Company_Profile,
    Equipment_Type_Get,
    Equipment_Type_Create,
    Equipment_Brand_Get,
    Equipment_Brand_Create,
    Customer_Create,
    Customer_Update,
    Customer_Get_All,
    Customer_Equipment_Create,
    Customer_Equipment_Get_All,
    Customer_Equipment_Get_Jobs,
    Customer_Equipment_Assign_Job,
    Job_Type_Create,
    Job_Type_Get,
    Job_Create,
    Job_Get_All,
    Job_Get_Technician,
    Job_Update,
    Job_Edit,
    Job_Start,
    Job_Finish,
    Job_Detail,
    Image_Upload,
    Group_Create,
    Group_Get_All,
    Group_Delete,
    Group_Add_Manager,
    Group_Add_Member,
    Group_Remove_Member,
    Company_Equipment_Create,
    Company_Equipment_Get,
    Company_Equipment_Check_In_Out,
    Inventory_Take,
    Inventory_Report,
    Company_Card_Add,
    Company_Card_Get,
    Company_Card_Remove,
    Tags_Place_Order,
    Tags_Get_Orders,
    Subscription_Buy,
    Subscription_Cancel,
    Start_Contract,
    Invite_Contractor,
    Accept_Reject_Contract,
    Cancel_Finish_Contract,
    Add_Contractor_Permission,
    Get_All_Contracts,
    Get_Company_Contracts,
    Get_Contractor_Detail,
    Upgrade_To_Company,
    Company_Subscribe,
    Custom_work_Order_Number,
    Customer_Import,
    Get_Service_Tickets,
    Create_Service_Ticket,
    Edit_Service_Ticket,
    Update_Service_Ticket,
    Get_Ticket_Detail,
    Get_Contractors_For_Job,
    Get_Customer_Detail,
    Get_Job_Report,
    Get_QB_Customers,
    Create_QB_customer,
    Scan_Tag,
    Get_Custom_Work_No,
    Get_QB_Uri,
    Get_Sync_Info,
    Create_Sales_Tax,
    Update_Sales_Tax,
    Delete_Sales_Tax,
    Get_Sales_Taxes,
    Set_Invoice_Number,
    Get_Current_Invoice_Number,
    Create_Job_Charges,
    Update_Job_Charges,
    Delete_Job_Charges,
    Get_Job_Charges,
    Create_Invoice,
    Update_Invoice,
    Get_Invoice_Detail,
    Get_Invoices,
    Get_Parts,
    Create_Part,
    Update_Part,
    Remove_Part,
    Create_Purchase_Order,
    Update_Purchase_Order,
    Update_Status_Purchase_Order,
    Create_Purchase_Order_From_Estimate,
    Get_Purchase_Order,
    Create_Estimate,
    Update_Estimate,
    Update_Status_Estimate,
    Get_Estimate,
    Cancel_Estimate,
    Get_Company_Contractor_Activity,
    Get_Items,
    Update_Item,
    Get_Equipment_Purchase_Order,
    Get_Customer_Invoices,
    Create_Payment,
    Update_Payment,
    Get_Customer_Payments,
    Get_Payments,
    Code_Location_Tag,
    Update_Location_Tag,
    Get_Location_Tags,
    Get_Location_Tag_Jobs
}

export const ContractorPermissions = {
    on: [
        Permissions.Equipment_Type_Get,
        Permissions.Equipment_Brand_Get,
        Permissions.Customer_Get_All,
        Permissions.Customer_Equipment_Create,
        Permissions.Customer_Equipment_Get_All,
        Permissions.Customer_Equipment_Get_Jobs,
        Permissions.Customer_Equipment_Assign_Job,
        Permissions.Job_Type_Get,
        Permissions.Job_Create,
        Permissions.Job_Get_All,
        Permissions.Job_Get_Technician,
        Permissions.Job_Update,
        Permissions.Job_Edit,
        Permissions.Job_Start,
        Permissions.Job_Finish,
        Permissions.Job_Detail,
        Permissions.Image_Upload,
        Permissions.Get_Service_Tickets,
        Permissions.Create_Service_Ticket,
        Permissions.Edit_Service_Ticket,
        Permissions.Update_Service_Ticket,
        Permissions.Get_Ticket_Detail,
        Permissions.Get_Customer_Detail
    ]
}
export const UserPermissions = {
    0: {
        on: [
            Permissions.Permission_Get_All,
            Permissions.Permission_Get_Office_Admin,
            Permissions.Permission_Get_Tech,
            Permissions.Permission_Get_Manager,
            Permissions.Permission_Get_Employee,
            Permissions.Permission_Update_Default,
            Permissions.Permission_Update_Employee,
            Permissions.User_Create_Manager,
            Permissions.User_Get_Manager,
            Permissions.User_Create_Technician,
            Permissions.User_Get_Technician,
            Permissions.User_Create_Office_Admin,
            Permissions.User_Get_Office_Admin,
            Permissions.User_Update_Profile,
            Permissions.User_Change_Password,
            Permissions.User_Delete_Employee,
            Permissions.User_Activate_Employee,
            Permissions.User_Get_All_Employees,
            Permissions.Update_Company_Profile,
            Permissions.Equipment_Type_Get,
            Permissions.Equipment_Type_Create,
            Permissions.Equipment_Brand_Get,
            Permissions.Equipment_Brand_Create,
            Permissions.Customer_Create,
            Permissions.Customer_Update,
            Permissions.Customer_Get_All,
            Permissions.Customer_Equipment_Create,
            Permissions.Customer_Equipment_Get_All,
            Permissions.Customer_Equipment_Get_Jobs,
            Permissions.Customer_Equipment_Assign_Job,
            Permissions.Job_Type_Create,
            Permissions.Job_Type_Get,
            Permissions.Job_Create,
            Permissions.Job_Get_All,
            Permissions.Job_Get_Technician,
            Permissions.Job_Update,
            Permissions.Job_Edit,
            Permissions.Job_Start,
            Permissions.Job_Finish,
            Permissions.Job_Detail,
            Permissions.Image_Upload,
            Permissions.Group_Create,
            Permissions.Group_Get_All,
            Permissions.Group_Delete,
            Permissions.Group_Add_Manager,
            Permissions.Group_Add_Member,
            Permissions.Group_Remove_Member,
            Permissions.Company_Equipment_Create,
            Permissions.Company_Equipment_Get,
            Permissions.Company_Equipment_Check_In_Out,
            Permissions.Inventory_Take,
            Permissions.Inventory_Report,
            Permissions.Company_Card_Add,
            Permissions.Company_Card_Get,
            Permissions.Company_Card_Remove,
            Permissions.Tags_Place_Order,
            Permissions.Tags_Get_Orders,
            Permissions.Subscription_Buy,
            Permissions.Subscription_Cancel,
            Permissions.Get_Service_Tickets,
            Permissions.Create_Service_Ticket,
            Permissions.Edit_Service_Ticket,
            Permissions.Update_Service_Ticket,
            Permissions.Get_Ticket_Detail,
            Permissions.Get_Contractors_For_Job,
            Permissions.Get_Customer_Detail,
            Permissions.Get_Job_Report,
            Permissions.Scan_Tag,
            Permissions.Get_Custom_Work_No,
            Permissions.Get_Sync_Info,
            Permissions.Create_Sales_Tax,
            Permissions.Update_Sales_Tax,
            Permissions.Delete_Sales_Tax,
            Permissions.Get_Sales_Taxes,
            Permissions.Set_Invoice_Number,
            Permissions.Get_Current_Invoice_Number,
            Permissions.Create_Job_Charges,
            Permissions.Update_Job_Charges,
            Permissions.Delete_Job_Charges,
            Permissions.Get_Job_Charges,
            Permissions.Create_Invoice,
            Permissions.Update_Invoice,
            Permissions.Get_Invoice_Detail,
            Permissions.Get_Invoices,
            Permissions.Get_Parts,
            Permissions.Create_Part,
            Permissions.Update_Part,
            Permissions.Remove_Part,
            Permissions.Create_Purchase_Order,
            Permissions.Update_Purchase_Order,
            Permissions.Update_Status_Purchase_Order,
            Permissions.Create_Purchase_Order_From_Estimate,
            Permissions.Get_Purchase_Order,
            Permissions.Create_Estimate,
            Permissions.Update_Estimate,
            Permissions.Update_Status_Estimate,
            Permissions.Get_Estimate,
            Permissions.Cancel_Estimate,
            Permissions.Get_Company_Contractor_Activity,
            Permissions.Get_Items,
            Permissions.Update_Item,
            Permissions.Get_Equipment_Purchase_Order,
            Permissions.Get_Customer_Invoices,
            Permissions.Create_Payment,
            Permissions.Update_Payment,
            Permissions.Get_Customer_Payments,
            Permissions.Get_Payments,
            Permissions.Code_Location_Tag,
            Permissions.Update_Location_Tag,
            Permissions.Get_Location_Tags,
            Permissions.Get_Location_Tag_Jobs,
            Permissions.Get_Company_Contracts
        ],
        off: [Permissions.None],
    },
    1: {
        on: [
            Permissions.Permission_Get_All,
            Permissions.Permission_Get_Office_Admin,
            Permissions.Permission_Get_Tech,
            Permissions.Permission_Get_Manager,
            Permissions.Permission_Get_Employee,
            Permissions.Permission_Update_Default,
            Permissions.Permission_Update_Employee,
            Permissions.User_Create_Manager,
            Permissions.User_Get_Manager,
            Permissions.User_Create_Technician,
            Permissions.User_Get_Technician,
            Permissions.User_Create_Office_Admin,
            Permissions.User_Get_Office_Admin,
            Permissions.User_Update_Profile,
            Permissions.User_Change_Password,
            Permissions.User_Delete_Employee,
            Permissions.User_Activate_Employee,
            Permissions.User_Get_All_Employees,
            Permissions.Update_Company_Profile,
            Permissions.Equipment_Type_Get,
            Permissions.Equipment_Type_Create,
            Permissions.Equipment_Brand_Get,
            Permissions.Equipment_Brand_Create,
            Permissions.Customer_Create,
            Permissions.Customer_Update,
            Permissions.Customer_Get_All,
            Permissions.Customer_Equipment_Create,
            Permissions.Customer_Equipment_Get_All,
            Permissions.Customer_Equipment_Get_Jobs,
            Permissions.Customer_Equipment_Assign_Job,
            Permissions.Job_Type_Create,
            Permissions.Job_Type_Get,
            Permissions.Job_Create,
            Permissions.Job_Get_All,
            Permissions.Job_Get_Technician,
            Permissions.Job_Update,
            Permissions.Job_Edit,
            Permissions.Job_Start,
            Permissions.Job_Finish,
            Permissions.Job_Detail,
            Permissions.Image_Upload,
            Permissions.Group_Create,
            Permissions.Group_Get_All,
            Permissions.Group_Delete,
            Permissions.Group_Add_Manager,
            Permissions.Group_Add_Member,
            Permissions.Group_Remove_Member,
            Permissions.Company_Equipment_Create,
            Permissions.Company_Equipment_Get,
            Permissions.Company_Equipment_Check_In_Out,
            Permissions.Inventory_Take,
            Permissions.Inventory_Report,
            Permissions.Company_Card_Add,
            Permissions.Company_Card_Get,
            Permissions.Company_Card_Remove,
            Permissions.Tags_Place_Order,
            Permissions.Tags_Get_Orders,
            Permissions.Subscription_Buy,
            Permissions.Subscription_Cancel,
            Permissions.Get_Service_Tickets,
            Permissions.Create_Service_Ticket,
            Permissions.Edit_Service_Ticket,
            Permissions.Update_Service_Ticket,
            Permissions.Get_Ticket_Detail,
            Permissions.Get_Contractors_For_Job,
            Permissions.Get_Customer_Detail,
            Permissions.Get_Job_Report,
            Permissions.Scan_Tag,
            Permissions.Get_Custom_Work_No,
            Permissions.Get_Sync_Info,
            Permissions.Create_Sales_Tax,
            Permissions.Update_Sales_Tax,
            Permissions.Delete_Sales_Tax,
            Permissions.Get_Sales_Taxes,
            Permissions.Set_Invoice_Number,
            Permissions.Get_Current_Invoice_Number,
            Permissions.Create_Job_Charges,
            Permissions.Update_Job_Charges,
            Permissions.Delete_Job_Charges,
            Permissions.Get_Job_Charges,
            Permissions.Create_Invoice,
            Permissions.Update_Invoice,
            Permissions.Get_Invoice_Detail,
            Permissions.Get_Invoices,
            Permissions.Get_Parts,
            Permissions.Create_Part,
            Permissions.Update_Part,
            Permissions.Remove_Part,
            Permissions.Create_Purchase_Order,
            Permissions.Update_Purchase_Order,
            Permissions.Update_Status_Purchase_Order,
            Permissions.Create_Purchase_Order_From_Estimate,
            Permissions.Get_Purchase_Order,
            Permissions.Create_Estimate,
            Permissions.Update_Estimate,
            Permissions.Update_Status_Estimate,
            Permissions.Get_Estimate,
            Permissions.Cancel_Estimate,
            Permissions.Get_Company_Contractor_Activity,
            Permissions.Get_Items,
            Permissions.Update_Item,
            Permissions.Get_Equipment_Purchase_Order,
            Permissions.Get_Customer_Invoices,
            Permissions.Create_Payment,
            Permissions.Update_Payment,
            Permissions.Get_Customer_Payments,
            Permissions.Get_Payments,
            Permissions.Code_Location_Tag,
            Permissions.Update_Location_Tag,
            Permissions.Get_Location_Tags,
            Permissions.Get_Location_Tag_Jobs,
            Permissions.Get_Company_Contracts
        ],
        off: [Permissions.None],
    },
    2: {
        on: [
            Permissions.Permission_Get_All,
            Permissions.Permission_Get_Office_Admin,
            Permissions.Permission_Get_Tech,
            Permissions.Permission_Get_Manager,
            Permissions.Permission_Get_Employee,
            Permissions.Permission_Update_Default,
            Permissions.Permission_Update_Employee,
            Permissions.User_Create_Manager,
            Permissions.User_Get_Manager,
            Permissions.User_Create_Technician,
            Permissions.User_Get_Technician,
            Permissions.User_Create_Office_Admin,
            Permissions.User_Get_Office_Admin,
            Permissions.User_Update_Profile,
            Permissions.User_Change_Password,
            Permissions.User_Delete_Employee,
            Permissions.User_Activate_Employee,
            Permissions.User_Get_All_Employees,
            Permissions.Update_Company_Profile,
            Permissions.Equipment_Type_Get,
            Permissions.Equipment_Type_Create,
            Permissions.Equipment_Brand_Get,
            Permissions.Equipment_Brand_Create,
            Permissions.Customer_Create,
            Permissions.Customer_Update,
            Permissions.Customer_Get_All,
            Permissions.Customer_Equipment_Create,
            Permissions.Customer_Equipment_Get_All,
            Permissions.Customer_Equipment_Get_Jobs,
            Permissions.Customer_Equipment_Assign_Job,
            Permissions.Job_Type_Create,
            Permissions.Job_Type_Get,
            Permissions.Job_Create,
            Permissions.Job_Get_All,
            Permissions.Job_Get_Technician,
            Permissions.Job_Update,
            Permissions.Job_Edit,
            Permissions.Job_Start,
            Permissions.Job_Finish,
            Permissions.Job_Detail,
            Permissions.Job_Start,
            Permissions.Job_Finish,
            Permissions.Job_Detail,
            Permissions.Image_Upload,
            Permissions.Group_Create,
            Permissions.Group_Get_All,
            Permissions.Group_Delete,
            Permissions.Group_Add_Manager,
            Permissions.Group_Add_Member,
            Permissions.Group_Remove_Member,
            Permissions.Company_Equipment_Create,
            Permissions.Company_Equipment_Get,
            Permissions.Company_Equipment_Check_In_Out,
            Permissions.Inventory_Take,
            Permissions.Inventory_Report,
            Permissions.Company_Card_Add,
            Permissions.Company_Card_Get,
            Permissions.Company_Card_Remove,
            Permissions.Tags_Place_Order,
            Permissions.Tags_Get_Orders,
            Permissions.Subscription_Buy,
            Permissions.Subscription_Cancel,
            Permissions.Get_Service_Tickets,
            Permissions.Create_Service_Ticket,
            Permissions.Edit_Service_Ticket,
            Permissions.Update_Service_Ticket,
            Permissions.Get_Ticket_Detail,
            Permissions.Get_Contractors_For_Job,
            Permissions.Get_Customer_Detail,
            Permissions.Get_Job_Report,
            Permissions.Scan_Tag,
            Permissions.Get_Custom_Work_No,
            Permissions.Get_Sync_Info,
            Permissions.Create_Sales_Tax,
            Permissions.Update_Sales_Tax,
            Permissions.Delete_Sales_Tax,
            Permissions.Get_Sales_Taxes,
            Permissions.Set_Invoice_Number,
            Permissions.Get_Current_Invoice_Number,
            Permissions.Create_Job_Charges,
            Permissions.Update_Job_Charges,
            Permissions.Delete_Job_Charges,
            Permissions.Get_Job_Charges,
            Permissions.Create_Invoice,
            Permissions.Update_Invoice,
            Permissions.Get_Invoice_Detail,
            Permissions.Get_Invoices,
            Permissions.Get_Parts,
            Permissions.Create_Part,
            Permissions.Update_Part,
            Permissions.Remove_Part,
            Permissions.Create_Purchase_Order,
            Permissions.Update_Purchase_Order,
            Permissions.Update_Status_Purchase_Order,
            Permissions.Create_Purchase_Order_From_Estimate,
            Permissions.Get_Purchase_Order,
            Permissions.Create_Estimate,
            Permissions.Update_Estimate,
            Permissions.Update_Status_Estimate,
            Permissions.Get_Estimate,
            Permissions.Cancel_Estimate,
            Permissions.Get_Company_Contractor_Activity,
            Permissions.Get_Items,
            Permissions.Get_Company_Contracts,
            Permissions.Update_Item,
            Permissions.Get_Equipment_Purchase_Order,
            Permissions.Get_Customer_Invoices,
            Permissions.Create_Payment,
            Permissions.Update_Payment,
            Permissions.Get_Customer_Payments,
            Permissions.Get_Payments,
            Permissions.Code_Location_Tag,
            Permissions.Update_Location_Tag,
            Permissions.Get_Location_Tags,
            Permissions.Get_Location_Tag_Jobs
        ],
        off: [Permissions.None],
    },
    3: {
        on: [
            Permissions.Permission_Get_All,
            Permissions.Permission_Get_Office_Admin,
            Permissions.Permission_Get_Tech,
            Permissions.Permission_Get_Manager,
            Permissions.Permission_Get_Employee,
            Permissions.Permission_Update_Default,
            Permissions.Permission_Update_Employee,
            Permissions.User_Create_Manager,
            Permissions.User_Get_Manager,
            Permissions.User_Create_Technician,
            Permissions.User_Get_Technician,
            Permissions.User_Create_Office_Admin,
            Permissions.User_Get_Office_Admin,
            Permissions.User_Update_Profile,
            Permissions.User_Change_Password,
            Permissions.User_Delete_Employee,
            Permissions.User_Activate_Employee,
            Permissions.User_Get_All_Employees,
            Permissions.Update_Company_Profile,
            Permissions.Equipment_Type_Get,
            Permissions.Equipment_Type_Create,
            Permissions.Equipment_Brand_Get,
            Permissions.Equipment_Brand_Create,
            Permissions.Customer_Create,
            Permissions.Customer_Update,
            Permissions.Customer_Get_All,
            Permissions.Customer_Equipment_Create,
            Permissions.Customer_Equipment_Get_All,
            Permissions.Customer_Equipment_Get_Jobs,
            Permissions.Customer_Equipment_Assign_Job,
            Permissions.Job_Type_Create,
            Permissions.Job_Type_Get,
            Permissions.Job_Create,
            Permissions.Job_Get_All,
            Permissions.Job_Get_Technician,
            Permissions.Job_Update,
            Permissions.Job_Edit,
            Permissions.Job_Start,
            Permissions.Job_Finish,
            Permissions.Job_Detail,
            Permissions.Image_Upload,
            Permissions.Group_Create,
            Permissions.Group_Get_All,
            Permissions.Group_Delete,
            Permissions.Group_Add_Manager,
            Permissions.Group_Add_Member,
            Permissions.Group_Remove_Member,
            Permissions.Company_Equipment_Create,
            Permissions.Company_Equipment_Get,
            Permissions.Company_Equipment_Check_In_Out,
            Permissions.Inventory_Take,
            Permissions.Inventory_Report,
            Permissions.Company_Card_Add,
            Permissions.Company_Card_Get,
            Permissions.Company_Card_Remove,
            Permissions.Tags_Place_Order,
            Permissions.Tags_Get_Orders,
            Permissions.Subscription_Buy,
            Permissions.Subscription_Cancel,
            Permissions.Start_Contract,
            Permissions.Invite_Contractor,
            Permissions.Add_Contractor_Permission,
            Permissions.Get_Company_Contracts,
            Permissions.Get_Contractor_Detail,
            Permissions.Cancel_Finish_Contract,
            Permissions.Company_Subscribe,
            Permissions.Custom_work_Order_Number,
            Permissions.Customer_Import,
            Permissions.Get_Service_Tickets,
            Permissions.Create_Service_Ticket,
            Permissions.Edit_Service_Ticket,
            Permissions.Update_Service_Ticket,
            Permissions.Get_Ticket_Detail,
            Permissions.Get_Contractors_For_Job,
            Permissions.Get_Customer_Detail,
            Permissions.Get_All_Contracts,
            Permissions.Accept_Reject_Contract,
            Permissions.Get_Job_Report,
            Permissions.Get_QB_Customers,
            Permissions.Create_QB_customer,
            Permissions.Scan_Tag,
            Permissions.Get_Custom_Work_No,
            Permissions.Get_QB_Uri,
            Permissions.Get_Sync_Info,
            Permissions.Create_Sales_Tax,
            Permissions.Update_Sales_Tax,
            Permissions.Delete_Sales_Tax,
            Permissions.Get_Sales_Taxes,
            Permissions.Set_Invoice_Number,
            Permissions.Get_Current_Invoice_Number,
            Permissions.Create_Job_Charges,
            Permissions.Update_Job_Charges,
            Permissions.Delete_Job_Charges,
            Permissions.Get_Job_Charges,
            Permissions.Create_Invoice,
            Permissions.Update_Invoice,
            Permissions.Get_Invoice_Detail,
            Permissions.Get_Invoices,
            Permissions.Get_Parts,
            Permissions.Create_Part,
            Permissions.Update_Part,
            Permissions.Remove_Part,
            Permissions.Create_Purchase_Order,
            Permissions.Update_Purchase_Order,
            Permissions.Update_Status_Purchase_Order,
            Permissions.Create_Purchase_Order_From_Estimate,
            Permissions.Get_Purchase_Order,
            Permissions.Create_Estimate,
            Permissions.Update_Estimate,
            Permissions.Update_Status_Estimate,
            Permissions.Get_Estimate,
            Permissions.Cancel_Estimate,
            Permissions.Get_Company_Contractor_Activity,
            Permissions.Get_Items,
            Permissions.Update_Item,
            Permissions.Get_Equipment_Purchase_Order,
            Permissions.Get_Customer_Invoices,
            Permissions.Create_Payment,
            Permissions.Update_Payment,
            Permissions.Get_Customer_Payments,
            Permissions.Get_Payments,
            Permissions.Code_Location_Tag,
            Permissions.Update_Location_Tag,
            Permissions.Get_Location_Tags,
            Permissions.Get_Location_Tag_Jobs
        ],
        off: [Permissions.None],
    }
}
